server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:54321/auth_db
    username: auth_user
    password: auth_pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: mzA0OTFlNzkwNzhlYzYzYjFkZTZjYWIwMTY0M2RkNWI0Yzg5
  expiration: 3600000
 