server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:54322/billing_db
    username: billing_user
    password: billing_pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

billing:
  currency: EUR
  tax-rate: 0.2


management:
  server:
    port: 9092
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    prometheus:
      enabled: true
  security:
    enabled: false

  flyway:
    enabled: true
    locations: classpath:db/migration