server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**
        - id: billing-service
          uri: http://localhost:8082
          predicates:
            - Path=/billing/**
        - id: user-service
          uri: http://localhost:8083
          predicates:
            - Path=/users/**
