server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://prod-db:5432/user_db
    username: prod_user
    password: prod_pass
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
