server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:54323/user_db
    username: user_user 
    password: user_pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


 